{{- if and .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "gitlab-ci-pipelines-exporter.fullname" . }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace | default .Release.Namespace }}
  labels: {{- include "gitlab-ci-pipelines-exporter.labels" . | nindent 4 }}
    {{- if .Values.metrics.serviceMonitor.labels -}}
    {{ .Values.metrics.serviceMonitor.labels | toYaml | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "gitlab-ci-pipelines-exporter.annotations" . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: http
      path: /metrics
      {{- if .Values.metrics.serviceMonitor.interval }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
      {{- tpl (.Values.metrics.serviceMonitor.relabelings | toYaml) $ | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
      {{- tpl (.Values.metrics.serviceMonitor.metricRelabelings | toYaml) $ | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "gitlab-ci-pipelines-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
